local recipes = {}

local ee = "emendatusenigmatica:"
local mc = "minecraft:"
local th = "thermal:"
local rs = "refinedstorage:"
local ug = "undergarden:"
local tc = "tconstruct:"
local ei = "eidolon:"
local cm = "compactmachines:"
local ars = "ars_nouveau:"
local fn = "fluxnetworks:"
local ie = "immersiveengineering:"
local bef = "betterendforge:"
local pn = "pneumaticcraft:"
local indf = "industrialforegoing:"
local cr = "create:"
local mk = "mekanism:"
local at = "atum:"
local qk = "quark:"
local ge = "glassential:"

recipes[ug.."froststeel_ingot"] = {3, th.."blizz_powder", 1, ee.."cobalt_ingot", 3}
recipes[ee.."electrum_ingot"] = {2, ee.."silver_ingot", 1, mc.."gold_ingot", 1}
recipes[th.."lumium_glass"] = {2, th.."obsidian_glass", 2, ee.."lumium_ingot", 1}
recipes[tc.."slimesteel_ingot"] = {2, tc.."sky_slime_ball", 1, mc.."iron_ingot", 1, tc.."seared_brick", 1}
recipes[tc.."hepatizon_ingot"] = {4, ee.."cobalt_ingot", 1, ee.."copper_ingot", 2, mc.."obsidian", 1}
recipes[ei.."pewter_ingot"] = {2, mc.."iron_ingot", 1, ee.."lead_ingot", 1}
recipes[ee.."signalum_ingot"] = {4, ee.."silver_ingot", 1, ee.."copper_ingot", 3, mc.."redstone", 4}
recipes[mc.."netherite_ingot"] = {1, mc.."gold_ingot", 2, mc.."netherite_scrap", 4}
recipes[th.."enderium_glass"] = {2, th.."obsidian_glass", 2, ee.."enderium_ingot", 1}
recipes[ee.."brass_ingot"] = {2, ee.."zinc_ingot", 1, ee.."copper_ingot", 1}
recipes[ee.."signalum_ingot"] = {4, ee.."silver_ingot", 1, ee.."copper_ingot", 3, mc.."redstone", 4}
recipes[cm.."wall"] = {6, ie.."coil_mv", 1, ars.."warding_stone", 6, fn.."flux_dust", 3}
recipes[tc.."manyullyn_ingot"] = {4, mc.."netherite_scrap", 1, ee.."cobalt_ingot", 3}
recipes[bef.."terminite_ingot"] = {1, ee.."ender_dust", 1, bef.."thallasium_ingot", 1}
recipes[rs.."quartz_enriched_iron"] = {2, mc.."quartz", 1, pn.."ingot_iron_compressed", 1}
recipes[th.."cured_rubber"] = {2, ee.."sulfur_dust", 1, indf.."dryrubber", 2}
recipes[tc.."pig_iron_ingot"] = {2, tc.."blood_slime_ball", 1, mc.."iron_ingot", 1, mc.."clay_ball", 1}
recipes[th.."obsidian_glass"] = {2, mc.."quartz", 1, mc.."obsidian", 1, mc.."sand", 1}
recipes[ee.."steel_ingot"] = {1, mc.."iron_ingot", 1, ee.."coke_dust", 1}
recipes[tc.."tinkers_bronze_ingot"] = {3, ee.."copper_ingot", 3, mc.."glass", 1}
recipes[tc.."queens_slime_ingot"] = {2, ee.."cobalt_ingot", 1, mc.."gold_ingot", 1, mc.."magma_cream", 1}
recipes[ee.."constantan_ingot"] = {2, ee.."copper_ingot", 1, ee.."nickel_ingot", 1}
recipes[cr.."andesite_alloy"] = {1, mc.."andesite", 1, mc.."iron_nugget", 1}
recipes[mk.."alloy_reinforced"] = {4, ee.."aluminum_ingot", 3, ee.."lithium_dust", 4, ee.."copper_ingot", 1}
recipes[ee.."invar_ingot"] = {3, mc.."iron_ingot", 2, ee.."nickel_ingot", 1}
recipes[tc.."scorched_brick"] = {2, mc.."soul_sand", 1, mc.."gravel", 1, mc.."magma_cream", 1}
recipes[ee.."bronze_ingot"] = {4, ee.."tin_ingot", 1, ee.."copper_ingot", 3}
recipes[tc.."rose_gold_ingot"] = {4, mc.."gold_ingot", 1, ee.."copper_ingot", 3}
recipes[tc.."seared_brick"] = {2, mc.."sand", 1, mc.."clay_ball", 1, mc.."gravel", 1}
recipes[ee.."enderium_ingot"] = {2, ee.."diamond_dust", 1, ee.."lead_ingot", 3, ee.."ender_dust", 2}
recipes[bef.."aeternium_ingot"] = {1, bef.."terminite_ingot", 1, mc.."netherite_ingot", 1}
recipes[th.."signalum_glass"] = {2, th.."obsidian_glass", 2, ee.."signalum_ingot", 1}
recipes[at.."crystal_glass"] = {2, qk.."white_crystal_cluster", 1, ge.."glass_ghostly", 1, at.."sand", 1}
recipes[ee.."lumium_ingot"] = {4, ee.."silver_ingot", 1, ee.."tin_ingot", 3, mc.."glowstone_dust", 2}

return recipes
